import React, { Component, useState, useEffect } from "react";

import "../styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import NavHeader from "../components/navheader";

import { FloatingWhatsApp } from "react-floating-whatsapp-button";
import "react-floating-whatsapp-button/dist/index.css";
import colors from "../styles/colors";
import Footer from "../components/Footer";

function MyApp({ Component, pageProps }: AppProps) {
  const [loading, setLoading] = useState(false);
  useEffect(() => {
    setLoading(true);
  }, []);
  return (
    <div style={{ height: "100%", backgroundColor: colors.background }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavHeader />
      <main>
        <Component {...pageProps} />
      </main>
      <Footer />
      {loading && <FloatingWhatsApp />}
    </div>
  );
}

export default MyApp;
