import "../styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import NavHeader from "../components/navheader";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavHeader />
      <main>
        <div style={{ height: "100vh", backgroundColor: "#ECF0F1" }}>
          <Component {...pageProps} />
        </div>
      </main>
      <footer>
        <span style={{ color: "red" }}>footer</span>
      </footer>
    </>
  );
}

export default MyApp;
