import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <span style={{ color: "red" }}>navheader</span>
      </header>
      <main>
      <Component {...pageProps} />
      </main>
      <footer>
        <span style={{ color: "red" }}>footer</span>
      </footer>
    </>
  );
}

export default MyApp
